package com.konakart.app;

/**
 *  The KonaKart Custom Engine - AddProductNotificationToCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class AddProductNotificationToCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public AddProductNotificationToCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void addProductNotificationToCustomer(String sessionId, int productId) throws KKException
     {
         kkEng.addProductNotificationToCustomer(sessionId, productId);
     }
}
