package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - ChangeDeliveryAddress - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class ChangeDeliveryAddress
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public ChangeDeliveryAddress(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrderIf changeDeliveryAddress(String sessionId, OrderIf order, AddressIf deliveryAddress) throws KKException
     {
         return kkEng.changeDeliveryAddress(sessionId, order, deliveryAddress);
     }
}
