package com.konakart.app;

/**
 *  The KonaKart Custom Engine - ChangeOrderStatus - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class ChangeOrderStatus
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public ChangeOrderStatus(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

      @Deprecated
     public void changeOrderStatus(String sessionId, int orderId, int status, boolean customerNotified, String comments) throws KKException
     {
         kkEng.changeOrderStatus(sessionId, orderId, status, customerNotified, comments);
     }
}
