package com.konakart.app;

/**
 *  The KonaKart Custom Engine - CustomSecure - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class CustomSecure
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public CustomSecure(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String customSecure(String sessionId, String input1, String input2) throws KKException
     {
         return kkEng.customSecure(sessionId, input1, input2);
     }
}
