package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - DeleteCustomerNotifications - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class DeleteCustomerNotifications
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public DeleteCustomerNotifications(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void deleteCustomerNotifications(NotificationOptionsIf options) throws KKException
     {
         kkEng.deleteCustomerNotifications(options);
     }
}
