package com.konakart.app;

/**
 *  The KonaKart Custom Engine - EnableCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class EnableCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public EnableCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void enableCustomer(String secretKey) throws KKException
     {
         kkEng.enableCustomer(secretKey);
     }
}
