package com.konakart.app;

/**
 *  The KonaKart Custom Engine - FreeReservedPoints - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class FreeReservedPoints
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public FreeReservedPoints(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int freeReservedPoints(String sessionId, int reservationId) throws KKException
     {
         return kkEng.freeReservedPoints(sessionId, reservationId);
     }
}
