package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAddressesPerCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAddressesPerCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAddressesPerCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public AddressIf[] getAddressesPerCustomer(String sessionId) throws KKException
     {
         return kkEng.getAddressesPerCustomer(sessionId);
     }
}
