package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAddressesPerProduct - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAddressesPerProduct
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAddressesPerProduct(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public AddressIf[] getAddressesPerProduct(int productId) throws KKException
     {
         return kkEng.getAddressesPerProduct(productId);
     }
}
