package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetBestSellers - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetBestSellers
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetBestSellers(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf[] getBestSellers(DataDescriptorIf dataDesc, int categoryId, int languageId) throws KKException
     {
         return kkEng.getBestSellers(dataDesc, categoryId, languageId);
     }
}
