package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetConfigurationValueAsBool - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationValueAsBool
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetConfigurationValueAsBool(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public Boolean getConfigurationValueAsBool(String key, Boolean def) throws KKException
     {
         return kkEng.getConfigurationValueAsBool(key, def);
     }
}
