package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCountry - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCountry
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCountry(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CountryIf getCountry(int countryId) throws KKException
     {
         return kkEng.getCountry(countryId);
     }
}
