package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCustomerTag - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerTag
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCustomerTag(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CustomerTagIf getCustomerTag(String sessionId, String tagName) throws KKException
     {
         return kkEng.getCustomerTag(sessionId, tagName);
     }
}
