package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetDefaultCurrency - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetDefaultCurrency
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetDefaultCurrency(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CurrencyIf getDefaultCurrency() throws KKException
     {
         return kkEng.getDefaultCurrency();
     }
}
