package com.konakart.app;

import java.util.Calendar;

/**
 *  The KonaKart Custom Engine - GetKonakartTimeStamp - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetKonakartTimeStamp
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetKonakartTimeStamp(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public Calendar getKonakartTimeStamp() throws KKException
     {
         return kkEng.getKonakartTimeStamp();
     }
}
