package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetLanguagePerCode - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetLanguagePerCode
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetLanguagePerCode(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public LanguageIf getLanguagePerCode(String code) throws KKException
     {
         return kkEng.getLanguagePerCode(code);
     }
}
