package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetLanguages - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetLanguages
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetLanguages(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public LanguageIf[] getLanguages(LanguageSearchIf search) throws KKException
     {
         return kkEng.getLanguages(search);
     }
}
