package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetMessages - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetMessages
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetMessages(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public NameValueIf[] getMessages(int type, String locale) throws KKException
     {
         return kkEng.getMessages(type, locale);
     }
}
