package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetManufacturersPerCategory - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetManufacturersPerCategory
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetManufacturersPerCategory(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ManufacturerIf[] getManufacturersPerCategory(int categoryId) throws KKException
     {
         return kkEng.getManufacturersPerCategory(categoryId);
     }
}
