package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetOrder - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetOrder
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetOrder(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrderIf getOrder(String sessionId, int orderId, int languageId) throws KKException
     {
         return kkEng.getOrder(sessionId, orderId, languageId);
     }
}
