package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetOrderHistoryWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetOrderHistoryWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetOrderHistoryWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf[] getOrderHistoryWithOptions(DataDescriptorIf dataDesc, String sessionId, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getOrderHistoryWithOptions(dataDesc, sessionId, languageId, options);
     }
}
