package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductsPerCategory - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductsPerCategory
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductsPerCategory(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getProductsPerCategory(String sessionId, DataDescriptorIf dataDesc, int categoryId, boolean searchInSubCats, int languageId) throws KKException
     {
         return kkEng.getProductsPerCategory(sessionId, dataDesc, categoryId, searchInSubCats, languageId);
     }
}
