package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetPunchOutMessage - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetPunchOutMessage
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetPunchOutMessage(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public PunchOutResultIf getPunchOutMessage(String sessionId, OrderIf order, PunchOutOptionsIf options) throws KKException
     {
         return kkEng.getPunchOutMessage(sessionId, order, options);
     }
}
