package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductsPerCategoryPerManufacturerWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductsPerCategoryPerManufacturerWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductsPerCategoryPerManufacturerWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getProductsPerCategoryPerManufacturerWithOptions(String sessionId, DataDescriptorIf dataDesc, int categoryId, int manufacturerId, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getProductsPerCategoryPerManufacturerWithOptions(sessionId, dataDesc, categoryId, manufacturerId, languageId, options);
     }
}
