package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetPaymentDetails - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetPaymentDetails
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetPaymentDetails(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public PaymentDetailsIf getPaymentDetails(String sessionId, String moduleCode, int orderId, String hostAndPort, int languageId) throws KKException
     {
         return kkEng.getPaymentDetails(sessionId, moduleCode, orderId, hostAndPort, languageId);
     }
}
