package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductNotificationsPerCustomerWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductNotificationsPerCustomerWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductNotificationsPerCustomerWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf[] getProductNotificationsPerCustomerWithOptions(String sessionId, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getProductNotificationsPerCustomerWithOptions(sessionId, languageId, options);
     }
}
