package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductsPerCategoryWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductsPerCategoryWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductsPerCategoryWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getProductsPerCategoryWithOptions(String sessionId, DataDescriptorIf dataDesc, int categoryId, boolean searchInSubCats, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getProductsPerCategoryWithOptions(sessionId, dataDesc, categoryId, searchInSubCats, languageId, options);
     }
}
