package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductPerSku - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductPerSku
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductPerSku(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf getProductPerSku(String sessionId, String sku, int languageId) throws KKException
     {
         return kkEng.getProductPerSku(sessionId, sku, languageId);
     }
}
