package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetStore - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetStore
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetStore(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public StoreIf getStore() throws KKException
     {
         return kkEng.getStore();
     }
}
