package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetSubscriptionsPerCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetSubscriptionsPerCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetSubscriptionsPerCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public SubscriptionIf[] getSubscriptionsPerCustomer(String sessionId) throws KKException
     {
         return kkEng.getSubscriptionsPerCustomer(sessionId);
     }
}
