package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetStoreIds - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetStoreIds
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetStoreIds(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String[] getStoreIds() throws KKException
     {
         return kkEng.getStoreIds();
     }
}
