package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetTagGroupsPerCategoryWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetTagGroupsPerCategoryWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetTagGroupsPerCategoryWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public TagGroupIf[] getTagGroupsPerCategoryWithOptions(int categoryId, int languageId, FetchTagGroupOptionsIf options) throws KKException
     {
         return kkEng.getTagGroupsPerCategoryWithOptions(categoryId, languageId, options);
     }
}
