package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetTempCustomerId - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetTempCustomerId
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetTempCustomerId(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int getTempCustomerId() throws KKException
     {
         return kkEng.getTempCustomerId();
     }
}
