package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetWishListWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetWishListWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetWishListWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public WishListIf getWishListWithOptions(String sessionId, int wishListId, AddToWishListOptionsIf options) throws KKException
     {
         return kkEng.getWishListWithOptions(sessionId, wishListId, options);
     }
}
