package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - InsertSubscription - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class InsertSubscription
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public InsertSubscription(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int insertSubscription(String sessionId, SubscriptionIf subscription) throws KKException
     {
         return kkEng.insertSubscription(sessionId, subscription);
     }
}
