package com.konakart.app;

/**
 *  The KonaKart Custom Engine - LoginByAdmin - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class LoginByAdmin
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public LoginByAdmin(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String loginByAdmin(String adminSession, int customerId) throws KKException
     {
         return kkEng.loginByAdmin(adminSession, customerId);
     }
}
