package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - MergeBasketsWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class MergeBasketsWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public MergeBasketsWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void mergeBasketsWithOptions(String sessionId, int customerFromId, AddToBasketOptionsIf options) throws KKException
     {
         kkEng.mergeBasketsWithOptions(sessionId, customerFromId, options);
     }
}
