package com.konakart.app;

/**
 *  The KonaKart Custom Engine - RemoveFromWishList - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class RemoveFromWishList
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public RemoveFromWishList(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void removeFromWishList(String sessionId, int wishListItemId) throws KKException
     {
         kkEng.removeFromWishList(sessionId, wishListItemId);
     }
}
