package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - RemoveFromBasket - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class RemoveFromBasket
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public RemoveFromBasket(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void removeFromBasket(String sessionId, int customerId, BasketIf item) throws KKException
     {
         kkEng.removeFromBasket(sessionId, customerId, item);
     }
}
