package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SearchForOrdersPerCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SearchForOrdersPerCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SearchForOrdersPerCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrdersIf searchForOrdersPerCustomer(String sessionId, DataDescriptorIf dataDesc, OrderSearchIf orderSearch, int languageId) throws KKException
     {
         return kkEng.searchForOrdersPerCustomer(sessionId, dataDesc, orderSearch, languageId);
     }
}
