package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SendNewPassword1 - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SendNewPassword1
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SendNewPassword1(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public EmailIf sendNewPassword1(String emailAddr, EmailOptionsIf options) throws KKException
     {
         return kkEng.sendNewPassword1(emailAddr, options);
     }
}
