package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SetCreditCardDetailsOnOrder - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SetCreditCardDetailsOnOrder
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SetCreditCardDetailsOnOrder(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void setCreditCardDetailsOnOrder(String sessionId, int orderId, CreditCardIf card) throws KKException
     {
         kkEng.setCreditCardDetailsOnOrder(sessionId, orderId, card);
     }
}
