package com.konakart.app;

/**
 *  The KonaKart Custom Engine - UpdateDigitalDownloadCount - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class UpdateDigitalDownloadCount
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public UpdateDigitalDownloadCount(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int updateDigitalDownloadCount(String sessionId, int productId) throws KKException
     {
         return kkEng.updateDigitalDownloadCount(sessionId, productId);
     }
}
