package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - UpdateBasketWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class UpdateBasketWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public UpdateBasketWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void updateBasketWithOptions(String sessionId, int customerId, BasketIf item, AddToBasketOptionsIf options) throws KKException
     {
         kkEng.updateBasketWithOptions(sessionId, customerId, item, options);
     }
}
