package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - WriteReview - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class WriteReview
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public WriteReview(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int writeReview(String sessionId, ReviewIf review) throws KKException
     {
         return kkEng.writeReview(sessionId, review);
     }
}
