package com.konakart.app;

/**
 *  The KonaKart Custom Engine - DeleteReservedPoints - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class DeleteReservedPoints
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public DeleteReservedPoints(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void deleteReservedPoints(String sessionId, int reservationId, String code, String description) throws KKException
     {
         kkEng.deleteReservedPoints(sessionId, reservationId, code, description);
     }
}
