package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - EditCustomerAddress - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class EditCustomerAddress
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public EditCustomerAddress(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void editCustomerAddress(String sessionId, AddressIf addr) throws KKException
     {
         kkEng.editCustomerAddress(sessionId, addr);
     }
}
