package com.konakart.app;

/**
 *  The KonaKart Custom Engine - EvaluateExpressionForGuest - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class EvaluateExpressionForGuest
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public EvaluateExpressionForGuest(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public boolean evaluateExpressionForGuest(int customerId, int expressionId, String expressionName) throws KKException
     {
         return kkEng.evaluateExpressionForGuest(customerId, expressionId, expressionName);
     }
}
