package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllManufacturers - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllManufacturers
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllManufacturers(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ManufacturerIf[] getAllManufacturers() throws KKException
     {
         return kkEng.getAllManufacturers();
     }
}
