package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllSpecials - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllSpecials
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllSpecials(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getAllSpecials(String sessionId, DataDescriptorIf dataDesc, int languageId) throws KKException
     {
         return kkEng.getAllSpecials(sessionId, dataDesc, languageId);
     }
}
