package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllCurrencies - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllCurrencies
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllCurrencies(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CurrencyIf[] getAllCurrencies() throws KKException
     {
         return kkEng.getAllCurrencies();
     }
}
