package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetBookableProductConflict - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetBookableProductConflict
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetBookableProductConflict(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf[] getBookableProductConflict(String sessionId, ProductIf bookableProd, BookableProductOptionsIf options) throws KKException
     {
         return kkEng.getBookableProductConflict(sessionId, bookableProd, options);
     }
}
