package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetDefaultCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetDefaultCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetDefaultCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CustomerIf getDefaultCustomer() throws KKException
     {
         return kkEng.getDefaultCustomer();
     }
}
