package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetOrderIdFromSecretKey - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetOrderIdFromSecretKey
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetOrderIdFromSecretKey(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int getOrderIdFromSecretKey(String secretKey) throws KKException
     {
         return kkEng.getOrderIdFromSecretKey(secretKey);
     }
}
