package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf getProductWithOptions(String sessionId, int productId, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getProductWithOptions(sessionId, productId, languageId, options);
     }
}
