package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetRewardPoints - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetRewardPoints
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetRewardPoints(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public RewardPointsIf getRewardPoints(String sessionId, DataDescriptorIf dataDesc) throws KKException
     {
         return kkEng.getRewardPoints(sessionId, dataDesc);
     }
}
