package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - InsertKKEvent - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class InsertKKEvent
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public InsertKKEvent(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int insertKKEvent(String sessionId, KKEventIf event) throws Exception
     {
         return kkEng.insertKKEvent(sessionId, event);
     }
}
