package com.konakart.app;

/**
 *  The KonaKart Custom Engine - SendWelcomeEmail - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SendWelcomeEmail
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SendWelcomeEmail(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

      @Deprecated
     public void sendWelcomeEmail(int customerId, String mailSubject, String countryCode) throws KKException
     {
         kkEng.sendWelcomeEmail(customerId, mailSubject, countryCode);
     }
}
