package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SetCookie - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SetCookie
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SetCookie(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void setCookie(KKCookieIf cookie) throws KKException
     {
         kkEng.setCookie(cookie);
     }
}
