package com.konakart.app;

/**
 *  The KonaKart Custom Engine - UpdateCachedConfigurations - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class UpdateCachedConfigurations
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public UpdateCachedConfigurations(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void updateCachedConfigurations() throws KKException
     {
         kkEng.updateCachedConfigurations();
     }
}
