package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - UpdateOrder - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class UpdateOrder
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public UpdateOrder(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void updateOrder(String sessionId, int orderId, int status, boolean customerNotified, String comments, OrderUpdateIf updateOrder) throws KKException
     {
         kkEng.updateOrder(sessionId, orderId, status, customerNotified, comments, updateOrder);
     }
}
