package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - AddToWishListWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class AddToWishListWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public AddToWishListWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int addToWishListWithOptions(String sessionId, WishListItemIf wishListItem, AddToWishListOptionsIf options) throws KKException
     {
         return kkEng.addToWishListWithOptions(sessionId, wishListItem, options);
     }
}
