package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - AddToBasket - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class AddToBasket
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public AddToBasket(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int addToBasket(String sessionId, int customerId, BasketIf item) throws KKException
     {
         return kkEng.addToBasket(sessionId, customerId, item);
     }
}
