package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - AddToBasketWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class AddToBasketWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public AddToBasketWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int addToBasketWithOptions(String sessionId, int customerId, BasketIf item, AddToBasketOptionsIf options) throws KKException
     {
         return kkEng.addToBasketWithOptions(sessionId, customerId, item, options);
     }
}
