package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - CreateOrderWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class CreateOrderWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public CreateOrderWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrderIf createOrderWithOptions(String sessionId, BasketIf[] basketItemArray, CreateOrderOptionsIf options, int languageId) throws KKException
     {
         return kkEng.createOrderWithOptions(sessionId, basketItemArray, options, languageId);
     }
}
