package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - CreateOrder - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class CreateOrder
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public CreateOrder(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrderIf createOrder(String sessionId, BasketIf[] basketItemArray, int languageId) throws KKException
     {
         return kkEng.createOrder(sessionId, basketItemArray, languageId);
     }
}
