package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - CreateWishListWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class CreateWishListWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public CreateWishListWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int createWishListWithOptions(String sessionId, WishListIf wishList, AddToWishListOptionsIf options) throws KKException
     {
         return kkEng.createWishListWithOptions(sessionId, wishList, options);
     }
}
