package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - EditDigitalDownload - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class EditDigitalDownload
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public EditDigitalDownload(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void editDigitalDownload(String sessionId, DigitalDownloadIf digitalDownload) throws KKException
     {
         kkEng.editDigitalDownload(sessionId, digitalDownload);
     }
}
