package com.konakart.app;

/**
 *  The KonaKart Custom Engine - EvaluateExpression - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class EvaluateExpression
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public EvaluateExpression(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public boolean evaluateExpression(String sessionId, int expressionId, String expressionName) throws KKException
     {
         return kkEng.evaluateExpression(sessionId, expressionId, expressionName);
     }
}
