package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllOrderStatuses - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllOrderStatuses
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllOrderStatuses(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrderStatusIf[] getAllOrderStatuses(int languageId) throws KKException
     {
         return kkEng.getAllOrderStatuses(languageId);
     }
}
