package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllPromotions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllPromotions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllPromotions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public PromotionIf[] getAllPromotions() throws KKException
     {
         return kkEng.getAllPromotions();
     }
}
