package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllCountries - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllCountries
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllCountries(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CountryIf[] getAllCountries() throws KKException
     {
         return kkEng.getAllCountries();
     }
}
