package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllCustomerGroups - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllCustomerGroups
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllCustomerGroups(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CustomerGroupIf[] getAllCustomerGroups(int languageId) throws KKException
     {
         return kkEng.getAllCustomerGroups(languageId);
     }
}
