package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetAddressFormatTemplate - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAddressFormatTemplate
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAddressFormatTemplate(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String getAddressFormatTemplate(int templateId) throws KKException
     {
         return kkEng.getAddressFormatTemplate(templateId);
     }
}
