package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllProducts - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllProducts
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllProducts(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getAllProducts(String sessionId, DataDescriptorIf dataDesc, int languageId) throws KKException
     {
         return kkEng.getAllProducts(sessionId, dataDesc, languageId);
     }
}
