package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllLanguages - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllLanguages
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllLanguages(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public LanguageIf[] getAllLanguages() throws KKException
     {
         return kkEng.getAllLanguages();
     }
}
