package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetBasketItemsPerCustomerWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetBasketItemsPerCustomerWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetBasketItemsPerCustomerWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public BasketIf[] getBasketItemsPerCustomerWithOptions(String sessionId, int customerId, int languageId, AddToBasketOptionsIf options) throws KKException
     {
         return kkEng.getBasketItemsPerCustomerWithOptions(sessionId, customerId, languageId, options);
     }
}
