package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetBestSellersWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetBestSellersWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetBestSellersWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf[] getBestSellersWithOptions(DataDescriptorIf dataDesc, int categoryId, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getBestSellersWithOptions(dataDesc, categoryId, languageId, options);
     }
}
