package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetBookingsPerCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetBookingsPerCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetBookingsPerCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public BookingsIf getBookingsPerCustomer(String sessionId, DataDescriptorIf dataDesc, BookableProductOptionsIf options) throws KKException
     {
         return kkEng.getBookingsPerCustomer(sessionId, dataDesc, options);
     }
}
