package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetBookingsPerProduct - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetBookingsPerProduct
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetBookingsPerProduct(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public BookingsIf getBookingsPerProduct(DataDescriptorIf dataDesc, int productId, BookableProductOptionsIf options) throws KKException
     {
         return kkEng.getBookingsPerProduct(dataDesc, productId, options);
     }
}
