package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetBundlesThatProductsBelongTo - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetBundlesThatProductsBelongTo
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetBundlesThatProductsBelongTo(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getBundlesThatProductsBelongTo(String sessionId, DataDescriptorIf dataDesc, int[] productIds, boolean exactMatch, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getBundlesThatProductsBelongTo(sessionId, dataDesc, productIds, exactMatch, languageId, options);
     }
}
