package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetCustomDataFromSession - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCustomDataFromSession
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCustomDataFromSession(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String getCustomDataFromSession(String sessionId, int position) throws KKException
     {
         return kkEng.getCustomDataFromSession(sessionId, position);
     }
}
