package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCurrency - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCurrency
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCurrency(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CurrencyIf getCurrency(String currencyCode) throws KKException
     {
         return kkEng.getCurrency(currencyCode);
     }
}
