package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCouponsPerCode - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCouponsPerCode
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCouponsPerCode(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CouponIf[] getCouponsPerCode(String couponCode, CouponOptionsIf options) throws KKException
     {
         return kkEng.getCouponsPerCode(couponCode, options);
     }
}
