package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCategoriesPerProduct - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCategoriesPerProduct
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCategoriesPerProduct(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CategoryIf[] getCategoriesPerProduct(int productId, int languageId) throws KKException
     {
         return kkEng.getCategoriesPerProduct(productId, languageId);
     }
}
