package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetConfigurationValue - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationValue
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetConfigurationValue(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String getConfigurationValue(String key) throws KKException
     {
         return kkEng.getConfigurationValue(key);
     }
}
