package com.konakart.app;

import java.math.BigDecimal;

/**
 *  The KonaKart Custom Engine - GetConfigurationValueAsBigDecimal - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationValueAsBigDecimal
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetConfigurationValueAsBigDecimal(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public BigDecimal getConfigurationValueAsBigDecimal(String key) throws KKException
     {
         return kkEng.getConfigurationValueAsBigDecimal(key);
     }
}
