package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCategoryTreeWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCategoryTreeWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCategoryTreeWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CategoryIf[] getCategoryTreeWithOptions(CategoryTreeOptionsIf options) throws KKException
     {
         return kkEng.getCategoryTreeWithOptions(options);
     }
}
