package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetContentType - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetContentType
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetContentType(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ContentTypeIf getContentType(int contentTypeId, int languageId) throws KKException
     {
         return kkEng.getContentType(contentTypeId, languageId);
     }
}
