package com.konakart.app;

import java.math.BigDecimal;

/**
 *  The KonaKart Custom Engine - GetConfigurationValueAsBigDecimalWithDefault - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationValueAsBigDecimalWithDefault
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetConfigurationValueAsBigDecimalWithDefault(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public BigDecimal getConfigurationValueAsBigDecimalWithDefault(String key, BigDecimal def) throws KKException
     {
         return kkEng.getConfigurationValueAsBigDecimalWithDefault(key, def);
     }
}
