package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetCustomerTagValue - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCustomerTagValue
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCustomerTagValue(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String getCustomerTagValue(String sessionId, String tagName) throws KKException
     {
         return kkEng.getCustomerTagValue(sessionId, tagName);
     }
}
