package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetContentTypes - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetContentTypes
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetContentTypes(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ContentTypeIf[] getContentTypes(int languageId) throws KKException
     {
         return kkEng.getContentTypes(languageId);
     }
}
