package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCountryPerName - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCountryPerName
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCountryPerName(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CountryIf getCountryPerName(String countryName) throws KKException
     {
         return kkEng.getCountryPerName(countryName);
     }
}
