package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetContents - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetContents
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetContents(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ContentSearchResultIf getContents(String sessionId, ContentSearchIf search, DataDescriptorIf dd) throws KKException
     {
         return kkEng.getContents(sessionId, search, dd);
     }
}
