package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetCategory - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetCategory
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetCategory(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public CategoryIf getCategory(int categoryId, int languageId) throws KKException
     {
         return kkEng.getCategory(categoryId, languageId);
     }
}
