package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetConfigurationValueAsIntWithDefault - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetConfigurationValueAsIntWithDefault
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetConfigurationValueAsIntWithDefault(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int getConfigurationValueAsIntWithDefault(String key, int def) throws KKException
     {
         return kkEng.getConfigurationValueAsIntWithDefault(key, def);
     }
}
