package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetDigitalDownloads - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetDigitalDownloads
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetDigitalDownloads(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public DigitalDownloadIf[] getDigitalDownloads(String sessionId) throws KKException
     {
         return kkEng.getDigitalDownloads(sessionId);
     }
}
