package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetDefaultLanguage - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetDefaultLanguage
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetDefaultLanguage(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public LanguageIf getDefaultLanguage() throws KKException
     {
         return kkEng.getDefaultLanguage();
     }
}
