package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetExpressionForGuest - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetExpressionForGuest
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetExpressionForGuest(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ExpressionIf getExpressionForGuest(int customerId, int expressionId, String expressionName) throws KKException
     {
         return kkEng.getExpressionForGuest(customerId, expressionId, expressionName);
     }
}
