package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetGeoZonesPerZone - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetGeoZonesPerZone
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetGeoZonesPerZone(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public GeoZoneIf[] getGeoZonesPerZone(ZoneIf zone) throws KKException
     {
         return kkEng.getGeoZonesPerZone(zone);
     }
}
