package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetKonaKartVersion - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetKonaKartVersion
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetKonaKartVersion(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String getKonaKartVersion() throws KKException
     {
         return kkEng.getKonaKartVersion();
     }
}
