package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetKKEvents - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetKKEvents
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetKKEvents(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public KKEventIf[] getKKEvents(String sessionId, KKEventSearchIf search, DataDescriptorIf desc) throws Exception
     {
         return kkEng.getKKEvents(sessionId, search, desc);
     }
}
