package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetLanguagePerId - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetLanguagePerId
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetLanguagePerId(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public LanguageIf getLanguagePerId(int languageId) throws KKException
     {
         return kkEng.getLanguagePerId(languageId);
     }
}
