package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetManufacturer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetManufacturer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetManufacturer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ManufacturerIf getManufacturer(int manufacturerId, int languageId) throws KKException
     {
         return kkEng.getManufacturer(manufacturerId, languageId);
     }
}
