package com.konakart.app;

/**
 *  The KonaKart Custom Engine - GetMsgValue - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetMsgValue
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetMsgValue(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String getMsgValue(String key, int type, String locale) throws KKException
     {
         return kkEng.getMsgValue(key, type, locale);
     }
}
