package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetManufacturers - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetManufacturers
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetManufacturers(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ManufacturerIf[] getManufacturers(DataDescriptorIf dataDesc, ManufacturerSearchIf search, int languageId) throws KKException
     {
         return kkEng.getManufacturers(dataDesc, search, languageId);
     }
}
