package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetOrdersPerCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetOrdersPerCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetOrdersPerCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrdersIf getOrdersPerCustomer(DataDescriptorIf dataDesc, String sessionId, int languageId) throws KKException
     {
         return kkEng.getOrdersPerCustomer(dataDesc, sessionId, languageId);
     }
}
