package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetOrderTotals - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetOrderTotals
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetOrderTotals(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public OrderIf getOrderTotals(OrderIf order, int languageId) throws KKException
     {
         return kkEng.getOrderTotals(order, languageId);
     }
}
