package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetPaymentGateway - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetPaymentGateway
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetPaymentGateway(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public PaymentDetailsIf getPaymentGateway(OrderIf order, String moduleName, int languageId) throws KKException
     {
         return kkEng.getPaymentGateway(order, moduleName, languageId);
     }
}
