package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetPaymentGateways - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetPaymentGateways
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetPaymentGateways(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public PaymentDetailsIf[] getPaymentGateways(OrderIf order, int languageId) throws KKException
     {
         return kkEng.getPaymentGateways(order, languageId);
     }
}
