package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductImages - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductImages
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductImages(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductImagesIf getProductImages(ProductImagesOptionsIf options) throws KKException
     {
         return kkEng.getProductImages(options);
     }
}
