package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetPromotionsPerProducts - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetPromotionsPerProducts
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetPromotionsPerProducts(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf[] getPromotionsPerProducts(String sessionId, int customerId, ProductIf[] products, PromotionIf[] promotions, String[] couponCodes, PromotionOptionsIf options) throws KKException
     {
         return kkEng.getPromotionsPerProducts(sessionId, customerId, products, promotions, couponCodes, options);
     }
}
