package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductsPerManufacturer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductsPerManufacturer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductsPerManufacturer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getProductsPerManufacturer(String sessionId, DataDescriptorIf dataDesc, int manufacturerId, int languageId) throws KKException
     {
         return kkEng.getProductsPerManufacturer(sessionId, dataDesc, manufacturerId, languageId);
     }
}
