package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetPromotionsPerCoupon - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetPromotionsPerCoupon
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetPromotionsPerCoupon(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public PromotionIf[] getPromotionsPerCoupon(String couponCode, int couponId, PromotionOptionsIf options) throws KKException
     {
         return kkEng.getPromotionsPerCoupon(couponCode, couponId, options);
     }
}
