package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductQuantityWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductQuantityWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductQuantityWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductQuantityIf getProductQuantityWithOptions(String encodedProductId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getProductQuantityWithOptions(encodedProductId, options);
     }
}
