package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductPerSkuWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductPerSkuWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductPerSkuWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductIf getProductPerSkuWithOptions(String sessionId, String sku, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getProductPerSkuWithOptions(sessionId, sku, languageId, options);
     }
}
