package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetProductsPerManufacturerWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetProductsPerManufacturerWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetProductsPerManufacturerWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getProductsPerManufacturerWithOptions(String sessionId, DataDescriptorIf dataDesc, int manufacturerId, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getProductsPerManufacturerWithOptions(sessionId, dataDesc, manufacturerId, languageId, options);
     }
}
