package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetPaymentDetailsCustom - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetPaymentDetailsCustom
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetPaymentDetailsCustom(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public PaymentDetailsIf getPaymentDetailsCustom(String sessionId, String moduleCode, NameValueIf[] parameters) throws KKException
     {
         return kkEng.getPaymentDetailsCustom(sessionId, moduleCode, parameters);
     }
}
