package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetRelatedProductsWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetRelatedProductsWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetRelatedProductsWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getRelatedProductsWithOptions(String sessionId, DataDescriptorIf dataDesc, int productId, int relationType, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.getRelatedProductsWithOptions(sessionId, dataDesc, productId, relationType, languageId, options);
     }
}
