package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetReviews - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetReviews
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetReviews(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ReviewsIf getReviews(DataDescriptorIf dataDesc, ReviewSearchIf search) throws KKException
     {
         return kkEng.getReviews(dataDesc, search);
     }
}
