package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetSpecialsPerCategory - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetSpecialsPerCategory
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetSpecialsPerCategory(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf getSpecialsPerCategory(String sessionId, DataDescriptorIf dataDesc, int categoryId, boolean searchInSubCats, int languageId) throws KKException
     {
         return kkEng.getSpecialsPerCategory(sessionId, dataDesc, categoryId, searchInSubCats, languageId);
     }
}
