package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetSuggestedSearchItems - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetSuggestedSearchItems
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetSuggestedSearchItems(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public SuggestedSearchItemIf[] getSuggestedSearchItems(String sessionId, SuggestedSearchOptionsIf options) throws KKException
     {
         return kkEng.getSuggestedSearchItems(sessionId, options);
     }
}
