package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetSuggestedSpellingItems - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetSuggestedSpellingItems
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetSuggestedSpellingItems(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public SuggestedSpellingItemIf[] getSuggestedSpellingItems(String sessionId, SuggestedSpellingOptionsIf options) throws KKException
     {
         return kkEng.getSuggestedSpellingItems(sessionId, options);
     }
}
