package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetTagGroupsPerCategory - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetTagGroupsPerCategory
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetTagGroupsPerCategory(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public TagGroupIf[] getTagGroupsPerCategory(int categoryId, boolean getProdCount, int languageId) throws KKException
     {
         return kkEng.getTagGroupsPerCategory(categoryId, getProdCount, languageId);
     }
}
