package com.konakart.app;

import java.math.BigDecimal;

/**
 *  The KonaKart Custom Engine - GetTax - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetTax
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetTax(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public BigDecimal getTax(BigDecimal cost, int countryId, int zoneId, int taxClassId) throws KKException
     {
         return kkEng.getTax(cost, countryId, zoneId, taxClassId);
     }
}
