package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetTagsPerCategory - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetTagsPerCategory
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetTagsPerCategory(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public TagIf[] getTagsPerCategory(int categoryId, boolean getProdCount, int languageId) throws KKException
     {
         return kkEng.getTagsPerCategory(categoryId, getProdCount, languageId);
     }
}
