package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetTagGroup - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetTagGroup
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetTagGroup(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public TagGroupIf getTagGroup(int tagGroupId, boolean getProdCount, int languageId) throws KKException
     {
         return kkEng.getTagGroup(tagGroupId, getProdCount, languageId);
     }
}
