package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetWishListItemsWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetWishListItemsWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetWishListItemsWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public WishListItemsIf getWishListItemsWithOptions(String sessionId, DataDescriptorIf dataDesc, int wishListId, int languageId, AddToWishListOptionsIf options) throws KKException
     {
         return kkEng.getWishListItemsWithOptions(sessionId, dataDesc, wishListId, languageId, options);
     }
}
