package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetWishListItems - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetWishListItems
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetWishListItems(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public WishListItemsIf getWishListItems(String sessionId, DataDescriptorIf dataDesc, int wishListId, int languageId) throws KKException
     {
         return kkEng.getWishListItems(sessionId, dataDesc, wishListId, languageId);
     }
}
