package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetWishListWithItems - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetWishListWithItems
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetWishListWithItems(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public WishListIf getWishListWithItems(String sessionId, int wishListId, int languageId) throws KKException
     {
         return kkEng.getWishListWithItems(sessionId, wishListId, languageId);
     }
}
