package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - InsertCustomerTagForGuest - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class InsertCustomerTagForGuest
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public InsertCustomerTagForGuest(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void insertCustomerTagForGuest(int customerId, CustomerTagIf tag) throws KKException
     {
         kkEng.insertCustomerTagForGuest(customerId, tag);
     }
}
