package com.konakart.app;

/**
 *  The KonaKart Custom Engine - InsertDigitalDownload - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class InsertDigitalDownload
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public InsertDigitalDownload(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int insertDigitalDownload(String sessionId, int productId) throws KKException
     {
         return kkEng.insertDigitalDownload(sessionId, productId);
     }
}
