package com.konakart.app;

/**
 *  The KonaKart Custom Engine - Login - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class Login
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public Login(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public String login(String emailAddr, String password) throws KKException
     {
         return kkEng.login(emailAddr, password);
     }
}
