package com.konakart.app;

/**
 *  The KonaKart Custom Engine - MergeBaskets - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class MergeBaskets
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public MergeBaskets(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void mergeBaskets(String sessionId, int customerFromId) throws KKException
     {
         kkEng.mergeBaskets(sessionId, customerFromId);
     }
}
