package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - MergeWishListsWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class MergeWishListsWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public MergeWishListsWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void mergeWishListsWithOptions(String sessionId, int customerFromId, int languageId, AddToWishListOptionsIf options) throws KKException
     {
         kkEng.mergeWishListsWithOptions(sessionId, customerFromId, languageId, options);
     }
}
