package com.konakart.app;

/**
 *  The KonaKart Custom Engine - PointsAvailable - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class PointsAvailable
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public PointsAvailable(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int pointsAvailable(String sessionId) throws KKException
     {
         return kkEng.pointsAvailable(sessionId);
     }
}
