package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - PostMessageToQueue - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class PostMessageToQueue
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public PostMessageToQueue(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void postMessageToQueue(String sessionId, MqOptionsIf options) throws KKException
     {
         kkEng.postMessageToQueue(sessionId, options);
     }
}
