package com.konakart.app;

/**
 *  The KonaKart Custom Engine - ProcessKKEvents - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class ProcessKKEvents
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public ProcessKKEvents(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void processKKEvents(String sessionId) throws Exception
     {
         kkEng.processKKEvents(sessionId);
     }
}
