package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - RegisterCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class RegisterCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public RegisterCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int registerCustomer(CustomerRegistrationIf custReg) throws KKException
     {
         return kkEng.registerCustomer(custReg);
     }
}
