package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - RemoveFromWishListWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class RemoveFromWishListWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public RemoveFromWishListWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void removeFromWishListWithOptions(String sessionId, int wishListItemId, AddToWishListOptionsIf options) throws KKException
     {
         kkEng.removeFromWishListWithOptions(sessionId, wishListItemId, options);
     }
}
