package com.konakart.app;

/**
 *  The KonaKart Custom Engine - RemoveBasketItemsPerCustomer - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class RemoveBasketItemsPerCustomer
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public RemoveBasketItemsPerCustomer(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void removeBasketItemsPerCustomer(String sessionId, int customerId) throws KKException
     {
         kkEng.removeBasketItemsPerCustomer(sessionId, customerId);
     }
}
