package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SaveIpnHistory - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SaveIpnHistory
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SaveIpnHistory(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int saveIpnHistory(String sessionId, IpnHistoryIf ipnHistory) throws KKException
     {
         return kkEng.saveIpnHistory(sessionId, ipnHistory);
     }
}
