package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SaveOrder - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SaveOrder
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SaveOrder(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int saveOrder(String sessionId, OrderIf order, int languageId) throws KKException
     {
         return kkEng.saveOrder(sessionId, order, languageId);
     }
}
