package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SearchForZones - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SearchForZones
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SearchForZones(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ZoneIf[] searchForZones(ZoneSearchIf search) throws KKException
     {
         return kkEng.searchForZones(search);
     }
}
