package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SearchForProductsWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SearchForProductsWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SearchForProductsWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductsIf searchForProductsWithOptions(String sessionId, DataDescriptorIf dataDesc, ProductSearchIf prodSearch, int languageId, FetchProductOptionsIf options) throws KKException
     {
         return kkEng.searchForProductsWithOptions(sessionId, dataDesc, prodSearch, languageId, options);
     }
}
