package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SearchForWishLists - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SearchForWishLists
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SearchForWishLists(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public WishListsIf searchForWishLists(String sessionId, DataDescriptorIf dataDesc, CustomerSearchIf customerSearch) throws KKException
     {
         return kkEng.searchForWishLists(sessionId, dataDesc, customerSearch);
     }
}
