package com.konakart.app;

/**
 *  The KonaKart Custom Engine - SendOrderConfirmationEmail - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SendOrderConfirmationEmail
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SendOrderConfirmationEmail(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

      @Deprecated
     public void sendOrderConfirmationEmail(String sessionId, int orderId, String mailSubject, int languageId) throws KKException
     {
         kkEng.sendOrderConfirmationEmail(sessionId, orderId, mailSubject, languageId);
     }
}
