package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - SendOrderConfirmationEmail1 - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SendOrderConfirmationEmail1
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SendOrderConfirmationEmail1(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public EmailIf sendOrderConfirmationEmail1(String sessionId, int orderId, int langIdForOrder, EmailOptionsIf options) throws KKException
     {
         return kkEng.sendOrderConfirmationEmail1(sessionId, orderId, langIdForOrder, options);
     }
}
