package com.konakart.app;

/**
 *  The KonaKart Custom Engine - SetRewardPointReservationId - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class SetRewardPointReservationId
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public SetRewardPointReservationId(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void setRewardPointReservationId(String sessionId, int orderId, int reservationId) throws KKException
     {
         kkEng.setRewardPointReservationId(sessionId, orderId, reservationId);
     }
}
