package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - UpdateBasketWithStockInfoWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class UpdateBasketWithStockInfoWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public UpdateBasketWithStockInfoWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public BasketIf[] updateBasketWithStockInfoWithOptions(BasketIf[] basketItems, AddToBasketOptionsIf options) throws KKException
     {
         return kkEng.updateBasketWithStockInfoWithOptions(basketItems, options);
     }
}
