package com.konakart.app;

/**
 *  The KonaKart Custom Engine - UpdateDigitalDownloadCountById - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class UpdateDigitalDownloadCountById
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public UpdateDigitalDownloadCountById(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public int updateDigitalDownloadCountById(String sessionId, int digitalDownloadId) throws KKException
     {
         return kkEng.updateDigitalDownloadCountById(sessionId, digitalDownloadId);
     }
}
