package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - UpdateInventoryWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class UpdateInventoryWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public UpdateInventoryWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void updateInventoryWithOptions(String sessionId, int orderId, CreateOrderOptionsIf options) throws KKException
     {
         kkEng.updateInventoryWithOptions(sessionId, orderId, options);
     }
}
