package com.konakart.app;

/**
 *  The KonaKart Custom Engine - ValidatePassword - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class ValidatePassword
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public ValidatePassword(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public boolean validatePassword(String sessionId, String password) throws KKException
     {
         return kkEng.validatePassword(sessionId, password);
     }
}
